# Project information
site_name: Bùi Hải Nam
site_description: Tổng hợp tài liệu học lập trình
site_author: Bùi Hải Nam
site_url: https://buihainam.com/

# Repository
repo_name: VNAPNIC/Learn-to-Code
repo_url: https://github.com/VNAPNIC/Learn-to-Code
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Bùi Hải Nam'

# Configuratio
theme:
  logo: 'img/logo.png'
  favicon: 'img/logo.png'
  name: material
  #custom_dir: 'mkdocs-material'
  # 404 page
  static_templates:
    - 404.html
    
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
    
  palette:
    primary: 'Cyan'
    accent: 'Cyan'
  font: false
    #text: 'Roboto Light'
    #code: 'Roboto Light'
  language: vi
  feature:
      tabs: false
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'globe'
      link: 'http://finishcoding.com/'
    - type: 'github'
      link: 'https://github.com/VNAPNIC'
    - type: 'facebook'
      link: 'https://www.facebook.com/NankaiNotes'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCECQ8GHamKx4H5jHMmNi2Ag'
      
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Google Analytics
google_analytics:
  - 'UA-139140751-1'
  - 'auto'

# Page tree
nav:
  - About: index.md
  - Kotlin:
    - Kotlin Basic: kotlin/kotlin_basic.md
    - Kotlin Class và kế thừa: kotlin/kotlin_class_inheritance.md
    - Kotlin Property và field: kotlin/kotlin_property_field.md
    - Kotlin Funtion: kotlin/kotlin_function.md
    - Kotlin Inteface: kotlin/kotlin_inteface.md
    - Kotlin Data class: kotlin/kotlin_data_class.md
    - Kotlin Nested class: kotlin/kotlin_nested_class.md
    - Kotlin Visibility Modifiers: kotlin/kotlin_visibility_modifiers.md
    - Kotlin Higher order funtion: kotlin/kotlin_higher_order_function.md
    - Kotlin Lambda: kotlin/kotlin_lambda.md
  - Dart:
    - Dart Cài đặt môi trường: dart/dart_environment_settings.md
    - Dart Basic: dart/dart_core.md
    - So sánh Dart và Swift: dart/dart_dart_vs_swift_a_comparison.md
    - Dart Async: dart/dart_async_intro.md
